# Generated by Django 3.1.6 on 2021-02-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentary',
            name='tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
