# Generated by Django 3.0.6 on 2020-05-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visitors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
