# Generated by Django 3.1.6 on 2021-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='embedded',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
