# Generated by Django 3.1.6 on 2021-03-11 15:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_site_embedded'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentary',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='documentary',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='web_documen_search__5c763a_gin'),
        ),
    ]
