# Generated by Django 3.1.6 on 2021-03-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210311_1539'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentary',
            index=models.Index(fields=['slug'], name='web_documen_slug_0b59dd_idx'),
        ),
    ]
