version: '3'
services:
  kiranadb:
    image: postgres:11
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kirana_db
  kirana:
    build:
      context: ../kirana
      dockerfile: ../docker/dev
    volumes:
      - ../kirana:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - kiranadb
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=unrecano@recano.club
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "8080:80"
    depends_on:
      - kiranadb
