version: '3'
services:
  documentariesdb:
    image: postgres:11
    ports:
      - "65432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: documentaries_db
  documentaries:
    build:
      context: ../documentaries
      dockerfile: ../docker/dev
    volumes:
      - ../documentaries:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - documentariesdb
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=unrecano@recano.club
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "8080:80"
    depends_on:
      - documentariesdb
