version: '3'
services:
  documentaries:
    build:
      context: ../documentaries
      dockerfile: ../docker/prod
    volumes:
      - ../documentaries:/code
    ports:
      - "8000:8000"
    env_file:
      - .env