# Generated by Django 3.0.7 on 2020-06-21 00:22

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('documentaries', models.ManyToManyField(related_name='searches', to='documentaries.Documentary')),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
    ]
